# Generated by Django 6.1 on 2026-08-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='line_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
