# Generated by Django 6.1 on 2026-08-24 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('sub_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_name', models.CharField(max_length=100)),
                ('sub_plan', models.CharField(blank=True, max_length=100)),
                ('sub_category', models.CharField(blank=True, max_length=50)),
                ('sub_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sub_cycle_value', models.PositiveIntegerField(default=1)),
                ('sub_cycle_unit', models.CharField(choices=[('day', 'วัน'), ('week', 'สัปดาห์'), ('month', 'เดือน'), ('year', 'ปี')], max_length=10)),
                ('sub_platform', models.CharField(blank=True, max_length=50)),
                ('pay_method', models.CharField(blank=True, max_length=50)),
                ('sub_start', models.DateField()),
                ('sub_next', models.DateField()),
                ('trial_status', models.BooleanField(default=False)),
                ('trial_end', models.DateField(blank=True, null=True)),
                ('alert_day', models.PositiveIntegerField(default=3)),
                ('sub_status', models.BooleanField(default=True)),
                ('sub_url', models.URLField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
