# Generated by Django 6.1 on 2026-08-24 20:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_alter_subscription_sub_cycle_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='sub_cycle_unit',
            field=models.CharField(blank=True, choices=[('day', 'วัน'), ('week', 'สัปดาห์'), ('month', 'เดือน'), ('year', 'ปี')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='sub_cycle_value',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='sub_next',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='sub_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
