# Generated by Django 6.1 on 2026-08-24 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notif_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('notif_type', models.CharField(max_length=30)),
                ('notif_title', models.CharField(max_length=100)),
                ('notif_text', models.CharField(max_length=255)),
                ('notif_date', models.DateTimeField()),
                ('notif_channel', models.CharField(choices=[('WEB', 'เว็บไซต์'), ('LINE', 'LINE')], max_length=10)),
                ('notif_url', models.CharField(blank=True, max_length=255)),
                ('notif_sent', models.DateTimeField(blank=True, null=True)),
                ('notif_status', models.IntegerField(choices=[(0, 'รอส่ง'), (1, 'ส่งแล้ว'), (2, 'ส่งไม่สำเร็จ')], default=0)),
                ('notif_read', models.BooleanField(default=False)),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='subscriptions.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
